version: "3.9"
services:
  db:
    image: postgres
    container_name: db_app
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - 6379:6379

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: bash -c "gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 9999:8000
    depends_on:
      db:
        condition: service_healthy